import pymysql

def make_db_connection():
    '''
    This Function Makes The Connection With The Database
    '''
    db = pymysql.connect(
        host="localhost",
        user="root",
        passwd="Rayan12345",
        database="scandifit",
    )
    return db

def insert_into_user(namn, email, password):
    '''
    This Function Inserts Values into user table
    '''
    # Make Database Connection
    db = make_db_connection()
    cursor = db.cursor()

    # Inserting User Values, and returning The Commit
    cursor.execute('insert into user (namn, email, password) values (%s, %s, %s)', (namn, email, password))
    db.commit()

    # Getting the latest autogenerated Id
    uid = cursor.lastrowid

    return uid

def add_phonenumber_to_user(uid, phonenumber):
    '''
    This Function Inserts Values into phonenumber table
    '''
    # Make Database Connection
    db = make_db_connection()
    cursor = db.cursor()

    # Inserting User Values, and returning The Commit
    cursor.execute('insert into phonenumber (uid, phonenumber) values (%s, %s)', (uid, phonenumber))
    db.commit()

def add_adress_to_user(uid, gatuadress, postnummer, stad):
    '''
    This Function Inserts Values into adress table
    '''
    # Make Database Connection
    db = make_db_connection()
    cursor = db.cursor()

    # Inserting User Values, and returning The Commit
    cursor.execute('insert into adress (uid, gatuadress, postnummer, stad) values (%s, %s, %s, %s)', (uid, gatuadress, postnummer, stad))
    db.commit()

def make_user_exklusiv(uid):
    '''
    This Function Inserts Values into exklusiv table
    '''
    # Make Database Connection
    db = make_db_connection()
    cursor = db.cursor()

    # Making User Exklusiv
    cursor.execute('insert into exklusiv (uid, exklusiv) values (%s, %s)', (uid, 1))
    db.commit()

def insert_info_trainingplan(uid, age, goal, body_type, problem_area, height, vikt, malvikt, gng_per_vecka, sjukdom, home_or_gym, utrustning):
    '''
    This Function Inserts Values into trainingplan table
    '''
    # Make Database Connection
    db = make_db_connection()
    cursor = db.cursor()

    cursor.execute('insert into trainingplan (uid, age, goal, body_type, problem_area, height, vikt, malvikt, gng_per_vecka, sjukdom, home_or_gym, utrustning) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)', (uid, age, goal, body_type, problem_area, height, vikt, malvikt, gng_per_vecka, sjukdom, home_or_gym, utrustning))
    db.commit()

from flask_mail import Mail

mail = Mail()