from flask import Blueprint, render_template, request, session, jsonify

from db import make_db_connection

from flask_mail import Mail, Message
from db import mail

login_register = Blueprint('login_register', __name__)

@login_register.route("/api/register", methods=['GET', 'POST'])
def register():
    print("Register endpoint hit")
    db = None
    cursor = None
    try:
        # Fetching info sent from frontend react
        data = request.get_json()

        name = data.get('name')
        email = data.get('email')
        phonenumber = data.get('phonenumber')
        password = data.get('password')
        
        if not all([name, email, password]):
            return jsonify({
                'success': False,
                'message': 'Missing required fields'
            })

        # Make Database Connection
        db = make_db_connection()
        cursor = db.cursor()

        cursor.execute('select * from "user" where email = %s', (email,))
        DoesEmailExist = cursor.fetchone()

        # Mail Check
        if DoesEmailExist:
            return jsonify(
                {
                    'success': False,
                    'message': f'Konot Med [{email}] Existerar Redan'
                }
            )
        else:

            # Inserting User Values Into User Table
            cursor.execute('insert into "user" (namn, email, "Password") values (%s, %s, %s)', (name, email, password))
            db.commit()

            # Getting the latest autogenerated Id
            uid = cursor.lastrowid

            # Logging Them In 
            session['user_id'] = uid

            # Did They enter a phone Number Or did they Leave It empty
            if phonenumber:
                cursor.execute('insert into "phonenumber" (uid, phonenumber) values (%s, %s)', (uid, phonenumber))
                db.commit()

            # for mail sending 
            msg = Message('Vi Har Tagit Emot Ditt Medelande', recipients=[email])
            msg.html = render_template('mail_welcome.html', namn=name)
            mail.send(msg)

            return jsonify(
                {
                    'success': True
                }
            )

    except:
        return jsonify({'success': False})
    finally:
        # Closing Database Connection
        if cursor:
            cursor.close()
        if db:
            db.close()
    
@login_register.route("/api/login", methods=['GET', 'POST'])
def login():
    try:
        # Fetching info sent from frontend react
        data = request.get_json()

        email = data.get('email')
        password = data.get('password')

        # Make Database Connection
        db = make_db_connection()
        cursor = db.cursor()
        print("Password provided:", password)
        
        cursor.execute('select * from "user" where "Password" = %s and email = %s', (password, email))
        user = cursor.fetchone()
        print(user)

        # Close Database Connection
        db.close()
        cursor.close()

        # authentication check
        if user:
            session['user_id'] = user[0]
            return jsonify({'success': True, 'id': user[0]})
        else:
            return jsonify({'success': False})
    except:
        return jsonify({'success': False})
    
@login_register.route('/api/protected', methods=['GET'])
def protected():
    if 'user_id' in session:
        return jsonify({'success': True})
    else:
        return jsonify({'success': False})